on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

name: Tests

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04]
        pyv: ["3.9"]

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.pyv }}

    - name: Install dependencies
      run: python -m pip install -e '.[tests]'

    - name: Test
      run: python -m pytest -v
      env:
        GDRIVE_USER_CREDENTIALS_DATA: ${{ secrets.GDRIVE_USER_CREDENTIALS_DATA }}
